### ISSUE TITLE
Mod crashing when hitting a Mob

### ISSUE THREAD

**Issue by Yoni664** [ChloePrime/HitFeedback#2]
[crash-2024-05-22_13.12.24-client.txt](https://github.com/ChloePrime/HitFeedback/files/15407769/crash-2024-05-22_13.12.24-client.txt)

**Comment by ChloePrime** [comment]
Try version 1.20.1-1.1.2

**Comment by Yoni664** [comment]
Thanks! The bug is solved with the last update!
